server:
  port: 9091

spring:
  freemarker:
    enabled: true
    charset: UTF-8
    suffix: .ftl
    content-type: text/html; charset=utf-8
    template-loader-path: classpath:/templates
  mvc:
    static-path-pattern: /static/**
